### ISSUE TITLE
Chrome 116

### ISSUE THREAD

**Issue by bostandyksoft** [sbtqa/chromedriver-bin#25]
После изменений политики выпуска chromedriver

For versions 115 and newer
Starting with M115 the ChromeDriver release process is integrated with that of Chrome. The latest Chrome + ChromeDriver releases per release channel (Stable, Beta, Dev, Canary) are available at the Chrome for Testing (CfT) availability dashboard. As a result, you might no longer have a need for version selection — you could choose any available CfT version and simply download the correspondingly-versioned ChromeDriver binary.

For automated version downloading one can use the convenient CfT JSON endpoints.

If you still have a need for version selection (e.g. to match a non-CfT Chrome binary with a compatible ChromeDriver binary), look up the Chrome binary’s MAJOR.MINOR.BUILD version in the latest-patch-versions-per-build JSON endpoints to find the corresponding ChromeDriver version.

Alternatively, you can use the LATEST_RELEASE_ endpoints at the new location.

Необходим механизм автоматической загрузки драйверов из новых истоников.

**Comment by clicman** [comment]
https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json downloads registry

**Comment by clicman** [comment]
Done
